import { db } from "./db.js";
import {
    LoanStatus,
    TransactionType,
    NotificationType,
    SavingType,
} from "./schema.js";
import { moduleService } from "../modules/service.js";

function generateId() {
    return Date.now() + Math.floor(Math.random() * 1000);
}

function daysFromNow(days) {
    const date = new Date();
    date.setDate(date.getDate() + days);
    return date;
}

function daysAgo(days) {
    const date = new Date();
    date.setDate(date.getDate() - days);
    return date;
}

export async function seedDatabase() {
    const cooperativeCount = await db.cooperatives.count();
    if (cooperativeCount > 0) {
        console.log("[Seed] Database already has data, skipping seed.");
        return false;
    }

    console.log("[Seed] Seeding demo data...");

    const cooperativeId = await db.cooperatives.add({
        name: "Koperasi Nusantara Maju",
        address: "Jl. Merdeka No. 45, Jakarta Selatan",
        phone: "021-7654321",
        cloudId: null,
        syncedAt: null,
    });

    const memberIds = await db.members.bulkAdd(
        [
            {
                cooperativeId,
                memberNumber: "KSP-0001",
                name: "Budi Santoso",
                phone: "081234567890",
                address: "Jl. Melati No. 12, Jakarta",
                status: "active",
                cloudId: null,
                syncedAt: null,
            },
            {
                cooperativeId,
                memberNumber: "KSP-0002",
                name: "Siti Nurhaliza",
                phone: "081234567891",
                address: "Jl. Anggrek No. 8, Jakarta",
                status: "active",
                cloudId: null,
                syncedAt: null,
            },
            {
                cooperativeId,
                memberNumber: "KSP-0003",
                name: "Ahmad Wijaya",
                phone: "081234567892",
                address: "Jl. Mawar No. 5, Jakarta",
                status: "active",
                cloudId: null,
                syncedAt: null,
            },
            {
                cooperativeId,
                memberNumber: "KSP-0004",
                name: "Dewi Lestari",
                phone: "081234567893",
                address: "Jl. Kenanga No. 15, Jakarta",
                status: "active",
                cloudId: null,
                syncedAt: null,
            },
            {
                cooperativeId,
                memberNumber: "KSP-0005",
                name: "Rudi Hermawan",
                phone: "081234567894",
                address: "Jl. Dahlia No. 22, Jakarta",
                status: "active",
                cloudId: null,
                syncedAt: null,
            },
        ],
        { allKeys: true },
    );

    await db.savings.bulkAdd([
        {
            memberId: memberIds[0],
            type: SavingType.DEPOSIT,
            amount: 500000,
            description: "Simpanan Wajib",
            status: "active",
            createdAt: daysAgo(115).toISOString(),
            cloudId: null,
            syncedAt: null,
        },
        {
            memberId: memberIds[0],
            type: SavingType.DEPOSIT,
            amount: 300000,
            description: "Simpanan Sukarela",
            status: "active",
            createdAt: daysAgo(85).toISOString(),
            cloudId: null,
            syncedAt: null,
        },
        {
            memberId: memberIds[1],
            type: SavingType.DEPOSIT,
            amount: 750000,
            description: "Simpanan Wajib",
            status: "active",
            createdAt: daysAgo(88).toISOString(),
            cloudId: null,
            syncedAt: null,
        },
        {
            memberId: memberIds[1],
            type: SavingType.DEPOSIT,
            amount: 400000,
            description: "Simpanan Sukarela",
            status: "active",
            createdAt: daysAgo(58).toISOString(),
            cloudId: null,
            syncedAt: null,
        },
        {
            memberId: memberIds[2],
            type: SavingType.DEPOSIT,
            amount: 600000,
            description: "Simpanan Wajib",
            status: "active",
            createdAt: daysAgo(55).toISOString(),
            cloudId: null,
            syncedAt: null,
        },
        {
            memberId: memberIds[3],
            type: SavingType.DEPOSIT,
            amount: 250000,
            description: "Simpanan Hari Raya",
            status: "active",
            createdAt: daysAgo(43).toISOString(),
            cloudId: null,
            syncedAt: null,
        },
        {
            memberId: memberIds[4],
            type: SavingType.DEPOSIT,
            amount: 1000000,
            description: "Simpanan Wajib",
            status: "active",
            createdAt: daysAgo(28).toISOString(),
            cloudId: null,
            syncedAt: null,
        },
    ]);

    await db.loans.bulkAdd([
        {
            memberId: memberIds[0],
            principal: 10000000,
            interestRate: 10,
            tenorMonths: 6,
            disbursementDate: daysAgo(30),
            status: LoanStatus.ACTIVE,
            approvedBy: null,
            approvedAt: daysAgo(28),
            notes: "Pinjaman modal kerja",
            cloudId: null,
            syncedAt: null,
        },
        {
            memberId: memberIds[1],
            principal: 5000000,
            interestRate: 10,
            tenorMonths: 3,
            disbursementDate: daysAgo(90),
            status: LoanStatus.COMPLETED,
            approvedBy: null,
            approvedAt: daysAgo(88),
            notes: "Lunas tepat waktu",
            cloudId: null,
            syncedAt: null,
        },
        {
            memberId: memberIds[2],
            principal: 15000000,
            interestRate: 12,
            tenorMonths: 12,
            disbursementDate: daysAgo(60),
            status: LoanStatus.ACTIVE,
            approvedBy: null,
            approvedAt: daysAgo(58),
            notes: "Pinjaman investasi",
            cloudId: null,
            syncedAt: null,
        },
        {
            memberId: memberIds[3],
            principal: 8000000,
            interestRate: 10,
            tenorMonths: 6,
            disbursementDate: daysAgo(95),
            status: LoanStatus.OVERDUE,
            approvedBy: null,
            approvedAt: daysAgo(93),
            notes: "Menunggu pengajuan baru",
            cloudId: null,
            syncedAt: null,
        },
    ]);

    const productIds = await db.products.bulkAdd(
        [
            {
                name: "Beras Premium 5kg",
                category: "Sembako",
                unit: "kg",
                purchasePrice: 65000,
                salePrice: 75000,
                barcode: null,
                minimumStock: 20,
                cloudId: null,
                syncedAt: null,
            },
            {
                name: "Minyak Goreng 2L",
                category: "Sembako",
                unit: "liter",
                purchasePrice: 28000,
                salePrice: 32000,
                barcode: null,
                minimumStock: 30,
                cloudId: null,
                syncedAt: null,
            },
            {
                name: "Gula Pasir 1kg",
                category: "Sembako",
                unit: "kg",
                purchasePrice: 12000,
                salePrice: 15000,
                barcode: null,
                minimumStock: 50,
                cloudId: null,
                syncedAt: null,
            },
            {
                name: "Telur Ayam 1kg",
                category: "Sembako",
                unit: "kg",
                purchasePrice: 24000,
                salePrice: 28000,
                barcode: null,
                minimumStock: 25,
                cloudId: null,
                syncedAt: null,
            },
            {
                name: "Sabun Mandi 100g",
                category: "Toiletries",
                unit: "pcs",
                purchasePrice: 6000,
                salePrice: 8000,
                barcode: null,
                minimumStock: 50,
                cloudId: null,
                syncedAt: null,
            },
            {
                name: "Sabun Cuci 900g",
                category: "Toiletries",
                unit: "pcs",
                purchasePrice: 15500,
                salePrice: 18500,
                barcode: null,
                minimumStock: 40,
                cloudId: null,
                syncedAt: null,
            },
            {
                name: "Shampo Botol 170ml",
                category: "Toiletries",
                unit: "pcs",
                purchasePrice: 18000,
                salePrice: 22000,
                barcode: null,
                minimumStock: 20,
                cloudId: null,
                syncedAt: null,
            },
            {
                name: "Pasta Gigi 150g",
                category: "Toiletries",
                unit: "pcs",
                purchasePrice: 10000,
                salePrice: 12500,
                barcode: null,
                minimumStock: 30,
                cloudId: null,
                syncedAt: null,
            },
        ],
        { allKeys: true },
    );

    await db.inventory.bulkAdd([
        {
            productId: productIds[0],
            stock: 85,
            minimumStock: 20,
            location: "Gudang A-1",
            updatedAt: daysAgo(1),
            cloudId: null,
            syncedAt: null,
        },
        {
            productId: productIds[1],
            stock: 120,
            minimumStock: 30,
            location: "Gudang A-1",
            updatedAt: daysAgo(1),
            cloudId: null,
            syncedAt: null,
        },
        {
            productId: productIds[2],
            stock: 200,
            minimumStock: 50,
            location: "Gudang A-2",
            updatedAt: daysAgo(1),
            cloudId: null,
            syncedAt: null,
        },
        {
            productId: productIds[3],
            stock: 75,
            minimumStock: 25,
            location: "Gudang A-2",
            updatedAt: daysAgo(1),
            cloudId: null,
            syncedAt: null,
        },
        {
            productId: productIds[4],
            stock: 300,
            minimumStock: 50,
            location: "Gudang B-1",
            updatedAt: daysAgo(1),
            cloudId: null,
            syncedAt: null,
        },
        {
            productId: productIds[5],
            stock: 150,
            minimumStock: 40,
            location: "Gudang B-1",
            updatedAt: daysAgo(1),
            cloudId: null,
            syncedAt: null,
        },
        {
            productId: productIds[6],
            stock: 8,
            minimumStock: 20,
            location: "Gudang B-2",
            updatedAt: daysAgo(0),
            cloudId: null,
            syncedAt: null,
        },
        {
            productId: productIds[7],
            stock: 95,
            minimumStock: 30,
            location: "Gudang B-2",
            updatedAt: daysAgo(1),
            cloudId: null,
            syncedAt: null,
        },
    ]);

    await db.transactions.bulkAdd([
        {
            cooperativeId,
            type: "income",
            cashierId: null,
            date: daysAgo(14),
            totalAmount: 150000,
            paymentMethod: "cash",
            status: "completed",
            cloudId: null,
            syncedAt: null,
        },
        {
            cooperativeId,
            type: "income",
            cashierId: null,
            date: daysAgo(12),
            totalAmount: 85000,
            paymentMethod: "cash",
            status: "completed",
            cloudId: null,
            syncedAt: null,
        },
        {
            cooperativeId,
            type: "income",
            cashierId: null,
            date: daysAgo(10),
            totalAmount: 2500000,
            paymentMethod: "cash",
            status: "completed",
            cloudId: null,
            syncedAt: null,
        },
        {
            cooperativeId,
            type: "income",
            cashierId: null,
            date: daysAgo(7),
            totalAmount: 320000,
            paymentMethod: "cash",
            status: "completed",
            cloudId: null,
            syncedAt: null,
        },
        {
            cooperativeId,
            type: "income",
            cashierId: null,
            date: daysAgo(5),
            totalAmount: 500000,
            paymentMethod: "cash",
            status: "completed",
            cloudId: null,
            syncedAt: null,
        },
        {
            cooperativeId,
            type: "income",
            cashierId: null,
            date: daysAgo(3),
            totalAmount: 15000000,
            paymentMethod: "transfer",
            status: "completed",
            cloudId: null,
            syncedAt: null,
        },
        {
            cooperativeId,
            type: "income",
            cashierId: null,
            date: daysAgo(2),
            totalAmount: 450000,
            paymentMethod: "cash",
            status: "completed",
            cloudId: null,
            syncedAt: null,
        },
        {
            cooperativeId,
            type: "income",
            cashierId: null,
            date: daysAgo(1),
            totalAmount: 275000,
            paymentMethod: "cash",
            status: "completed",
            cloudId: null,
            syncedAt: null,
        },
    ]);

    await db.notifications.bulkAdd([
        {
            type: NotificationType.INFO,
            title: "Sinkronisasi Berhasil",
            message:
                "Data berhasil disinkronkan ke server. 47 record baru telah diperbarui.",
            read: false,
            createdAt: daysAgo(0),
            cloudId: null,
            syncedAt: null,
        },
        {
            type: NotificationType.WARNING,
            title: "Stok Menipis",
            message:
                "Shampo Botol 170ml tinggal 8 unit. Segera lakukan restok.",
            read: false,
            createdAt: daysAgo(0),
            cloudId: null,
            syncedAt: null,
        },
        {
            type: NotificationType.ERROR,
            title: "Pinjaman Jatuh Tempo",
            message:
                "Pinjaman Dewi Lestari sudah melampaui batas tempo. Total kewajiban Rp 8.800.000.",
            read: false,
            createdAt: daysAgo(1),
            cloudId: null,
            syncedAt: null,
        },
        {
            type: NotificationType.SUCCESS,
            title: "Pinjaman Lunas",
            message:
                "Pinjaman Siti Nurhaliza sebesar Rp 5.500.000 telah lunas dibayar.",
            read: true,
            createdAt: daysAgo(10),
            cloudId: null,
            syncedAt: null,
        },
    ]);

    await db.settings.bulkAdd([
        { key: "cooperative_name", value: "Koperasi Nusantara Maju" },
        { key: "currency", value: "IDR" },
        { key: "locale", value: "id-ID" },
        { key: "theme", value: "light" },
        { key: "auto_sync", value: "true" },
        { key: "sync_interval", value: "300000" },
    ]);

    await db.customers.bulkAdd([
        {
            name: "Toko Sembako Jaya",
            contact: "Bpk. Agus Salim",
            phone: "081298765001",
            email: "agus@toko-jaya.co.id",
            address: "Jl. Kembang Jepun No. 88, Surabaya",
            category: "Pedagang Besar",
            totalTransaction: 250000000,
            visitCount: 45,
            lastVisit: daysAgo(0).toISOString().split("T")[0],
            status: "active",
            cloudId: null,
            syncedAt: null,
        },
        {
            name: "Warung Bu Rahma",
            contact: "Ibu. Rahma Wati",
            phone: "081298765002",
            email: "rahma@warungrahma.com",
            address: "Jl. Dupak No. 22, Surabaya",
            category: "Pedagang Kecil",
            totalTransaction: 85000000,
            visitCount: 32,
            lastVisit: daysAgo(1).toISOString().split("T")[0],
            status: "active",
            cloudId: null,
            syncedAt: null,
        },
        {
            name: "PT Cahaya Mandiri",
            contact: "Bpk. Hendro Wijaya",
            phone: "081298765003",
            email: "hendro@cahayamandiri.com",
            address: "Jl. Tambak Sawah No. 15, Sidoarjo",
            category: "Perusahaan",
            totalTransaction: 420000000,
            visitCount: 28,
            lastVisit: daysAgo(2).toISOString().split("T")[0],
            status: "active",
            cloudId: null,
            syncedAt: null,
        },
        {
            name: "Toko Kita",
            contact: "Ibu. Dina Kartika",
            phone: "081298765004",
            email: "dina@tokokita.id",
            address: "Jl. Priok No. 44, Surabaya",
            category: "Pedagang Besar",
            totalTransaction: 156000000,
            visitCount: 19,
            lastVisit: daysAgo(3).toISOString().split("T")[0],
            status: "active",
            cloudId: null,
            syncedAt: null,
        },
        {
            name: "Pelanggan Umum",
            contact: "-",
            phone: "081298765005",
            email: "-",
            address: "-",
            category: "Umum",
            totalTransaction: 12500000,
            visitCount: 8,
            lastVisit: daysAgo(5).toISOString().split("T")[0],
            status: "active",
            cloudId: null,
            syncedAt: null,
        },
    ]);

    await db.suppliers.bulkAdd([
        {
            name: "PT Sumber Makmur",
            contact: "Bpk. Hendra Wijaya",
            phone: "081234567100",
            email: "hendra@sumbermakmur.co.id",
            address: "Jl. Industri Raya No. 45, Surabaya",
            category: "Sembako",
            totalTransaction: 125000000,
            rating: 4.8,
            status: "active",
            cloudId: null,
            syncedAt: null,
        },
        {
            name: "CV Tiga Dara",
            contact: "Ibu. Sari Dewi",
            phone: "081234567101",
            email: "sari@tigadara.com",
            address: "Jl. Pelni No. 88, Sidoarjo",
            category: "Minuman",
            totalTransaction: 89500000,
            rating: 4.5,
            status: "active",
            cloudId: null,
            syncedAt: null,
        },
        {
            name: "PT Berkah Tani",
            contact: "Bpk. Ahmad Fauzi",
            phone: "081234567102",
            email: "ahmad@berkahtani.id",
            address: "Jl. Tani Utama No. 12, Gresik",
            category: "Pertanian",
            totalTransaction: 67000000,
            rating: 4.2,
            status: "active",
            cloudId: null,
            syncedAt: null,
        },
        {
            name: "UD Saujana",
            contact: "Bpk. Budi Santoso",
            phone: "081234567103",
            email: "budi@saujana.co.id",
            address: "Jl. Pasuruan No. 33, Pasuruan",
            category: "Sembako",
            totalTransaction: 45300000,
            rating: 4.0,
            status: "active",
            cloudId: null,
            syncedAt: null,
        },
        {
            name: "PT Cahaya Packaging",
            contact: "Ibu. Rina Kusuma",
            phone: "081234567104",
            email: "rina@cahayapack.com",
            address: "Jl. Packaging No. 7, Surabaya",
            category: "Kemasan",
            totalTransaction: 32100000,
            rating: 3.8,
            status: "inactive",
            cloudId: null,
            syncedAt: null,
        },
    ]);

    await db.procurements.bulkAdd([
        {
            date: daysAgo(0).toISOString().split("T")[0],
            supplierId: 1,
            supplier: "PT Sumber Makmur",
            product: "Beras Premium 5kg",
            quantity: 100,
            unitPrice: 68000,
            total: 6800000,
            status: "pending",
            method: "transfer",
            cloudId: null,
            syncedAt: null,
        },
        {
            date: daysAgo(1).toISOString().split("T")[0],
            supplierId: 2,
            supplier: "CV Tiga Dara",
            product: "Minyak Goreng 1L",
            quantity: 200,
            unitPrice: 16500,
            total: 3300000,
            status: "approved",
            method: "transfer",
            cloudId: null,
            syncedAt: null,
        },
        {
            date: daysAgo(2).toISOString().split("T")[0],
            supplierId: 3,
            supplier: "PT Berkah Tani",
            product: "Pupuk Organik 25kg",
            quantity: 50,
            unitPrice: 125000,
            total: 6250000,
            status: "received",
            method: "cash",
            cloudId: null,
            syncedAt: null,
        },
        {
            date: daysAgo(3).toISOString().split("T")[0],
            supplierId: 4,
            supplier: "UD Saujana",
            product: "Gula Pasir 50kg",
            quantity: 80,
            unitPrice: 13500,
            total: 1080000,
            status: "pending",
            method: "transfer",
            cloudId: null,
            syncedAt: null,
        },
    ]);

    await db.transactions.bulkAdd([
        {
            cooperativeId,
            type: "sale",
            items: [
                { id: 1, name: "Beras Premium 5kg", price: 75000, qty: 2 },
                { id: 3, name: "Gula Pasir 1kg", price: 15000, qty: 1 },
            ],
            subtotal: 165000,
            discount: 0,
            discountAmount: 0,
            tax: 18150,
            total: 183150,
            paymentMethod: "cash",
            status: "completed",
            createdAt: daysAgo(0).toISOString(),
            cloudId: null,
            syncedAt: null,
        },
        {
            cooperativeId,
            type: "sale",
            items: [
                { id: 2, name: "Minyak Goreng 2L", price: 32000, qty: 3 },
            ],
            subtotal: 96000,
            discount: 10,
            discountAmount: 9600,
            tax: 9504,
            total: 95904,
            paymentMethod: "qris",
            status: "completed",
            createdAt: daysAgo(1).toISOString(),
            cloudId: null,
            syncedAt: null,
        },
        {
            cooperativeId,
            type: "sale",
            items: [
                { id: 5, name: "Sabun Mandi 100g", price: 8000, qty: 5 },
                { id: 7, name: "Shampo Botol 170ml", price: 22000, qty: 2 },
            ],
            subtotal: 84000,
            discount: 0,
            discountAmount: 0,
            tax: 9240,
            total: 93240,
            paymentMethod: "transfer",
            status: "completed",
            createdAt: daysAgo(2).toISOString(),
            cloudId: null,
            syncedAt: null,
        },
    ]);

    await db.savings.bulkAdd([
        {
            memberId: memberIds[0],
            type: "deposit",
            amount: 500000,
            description: "Simpanan Wajib",
            createdAt: daysAgo(0).toISOString(),
            cloudId: null,
            syncedAt: null,
        },
        {
            memberId: memberIds[1],
            type: "deposit",
            amount: 750000,
            description: "Simpanan Sukarela",
            createdAt: daysAgo(1).toISOString(),
            cloudId: null,
            syncedAt: null,
        },
        {
            memberId: memberIds[2],
            type: "withdrawal",
            amount: 200000,
            description: "Penarikan",
            createdAt: daysAgo(2).toISOString(),
            cloudId: null,
            syncedAt: null,
        },
        {
            memberId: memberIds[0],
            type: "deposit",
            amount: 300000,
            description: "Simpanan Wajib",
            createdAt: daysAgo(3).toISOString(),
            cloudId: null,
            syncedAt: null,
        },
    ]);

    console.log("[Seed] Demo data seeded successfully.");

    await moduleService.initializeModules();

    return true;
}

export async function resetDatabase() {
    await db.delete();
    await db.open();
    await moduleService.initializeModules();
    await seedDatabase();
}
